timezone: Europe/Belgrade
permalink: /:title/
plugins:
  - jekyll-gist

defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME